---
# tasks file for tomcat-ansible-role

- name: Setup server.xml
  template:
    src: "{{ tomcat_template_server }}"
    dest: "{{ tomcat_install_path }}/apache-tomcat-{{ tomcat_version }}/conf/server.xml"
  notify: restart tomcat

- name: Setup tomcat-users.xml
  template:
    src: "{{ tomcat_template_users }}"
    dest: "{{ tomcat_install_path }}/apache-tomcat-{{ tomcat_version }}/conf/tomcat-users.xml"
  notify: restart tomcat

- name: Create symlink {{ tomcat_install_path }}/apache-tomcat-{{ tomcat_version }} to {{ tomcat_install_path }}/{{ tomcat_service_name }}
  file:
    src: "{{ tomcat_install_path }}/apache-tomcat-{{ tomcat_version }}"
    dest: "{{ tomcat_install_path }}/{{ tomcat_service_name }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    state: link

- name: Set non production permissions
  include: set-permissions.yml
  when: >
    tomcat_installed is changed or tomcat_permissions_ensure_on_every_run

- name: Delete webapps dir
  file:
    path: "{{ tomcat_install_path }}/{{ tomcat_service_name }}/webapps"
    state: absent
    
- name: Configure service file {{ tomcat_service_name }}.service
  template:
    src: "{{ tomcat_template_systemd_service }}"
    dest: /usr/lib/systemd/system/{{ tomcat_service_name }}.service
  notify: restart tomcat

- name: Configure logrotate file {{ tomcat_service_name }}
  template:
    src: "{{ tomcat_template_logrotate }}"
    dest: /etc/logrotate.d/{{ tomcat_service_name }}

- name: Enable tomcat service on startup
  systemd:
    name: "{{ tomcat_service_name }}"
    enabled: "{% if tomcat_service_enabled_on_startup %}yes{% else %}no{% endif %}"
    daemon_reload: yes
